{
 "title": "Daily View",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "⚡️ Electricity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production vs. Consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1 hour', s.t) + interval '20 minutes' as time,\n  ROUND((sum(s.i * s.p) / 3600 / 1000)::numeric, 3) as \"Consumption per 1h\"\nFROM (\n  SELECT\n    time as t,\n    ROUND(EXTRACT(EPOCH FROM (time - lag(time) OVER ())::interval)) as i,\n    (house_power + lag(house_power) OVER ()) / 2 as p\n  FROM\n    electricity_consumption\n  WHERE\n    $__timeFilter(\"time\")\n  ORDER BY time ASC\n) AS s\nGROUP BY time\nORDER BY time DESC"
    },
    {
     "rawSql": "SELECT\n  time_bucket('1 hour', s.t) as time,\n  ROUND((sum(s.i * s.p) / 3600 / 1000)::numeric, 3) as \"Production per 1h\"\nFROM (\n  SELECT\n    time as t,\n    ROUND(EXTRACT(EPOCH FROM (time - lag(time) OVER ())::interval)) as i,\n    (power + lag(power) OVER ()) / 2 as p\n  FROM\n    electricity_production\n  WHERE\n    $__timeFilter(\"time\")\n  ORDER BY time ASC\n) AS s\nGROUP BY time\nORDER BY time DESC"
    },
    {
     "rawSql": "SELECT\n  time_bucket('1 day', s.t) + interval '12 hours' as time,\n  ROUND((sum(s.i * s.p) / 3600 / 1000)::numeric, 3) as \"Production\"\nFROM (\n  SELECT\n    time as t,\n    ROUND(EXTRACT(EPOCH FROM (time - lag(time) OVER ())::interval)) as i,\n    (power + lag(power) OVER ()) / 2 as p\n  FROM\n    electricity_production\n  WHERE\n    $__timeFilter(\"time\")\n  ORDER BY time ASC\n) AS s\nGROUP BY time\nORDER BY time DESC"
    },
    {
     "rawSql": "SELECT\n  time_bucket('1 day', s.t) + interval '12 hours' as time,\n  ROUND((sum(s.i * s.p) / 3600 / 1000)::numeric, 3) as \"Consumption\"\nFROM (\n  SELECT\n    time as t,\n    ROUND(EXTRACT(EPOCH FROM (time - lag(time) OVER ())::interval)) as i,\n    (house_power + lag(house_power) OVER ()) / 2 as p\n  FROM\n    electricity_consumption\n  WHERE\n    $__timeFilter(\"time\")\n  ORDER BY time ASC\n) AS s\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Battery State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket_time as time,\n  soc as \"Average per day\",\n  max_soc as \"Max\",\n  min_soc as \"Min\"\nFROM (\n  SELECT\n    time_bucket('1 day', time) + interval '12 hours' as bucket_time,\n    avg(state_of_charge) as soc,\n    max(state_of_charge) as max_soc,\n    min(state_of_charge) as min_soc\n  FROM electricity_storage\n  WHERE\n    state_of_charge > 0 AND\n    $__timeFilter(\"time\")\n  GROUP BY bucket_time\n  ORDER BY bucket_time DESC\n) AS s\n"
    },
    {
     "rawSql": "SELECT\n  bucket_time as time,\n  soc as \"Average per 2h\"\nFROM (\n  SELECT\n    time_bucket('2h', time) as bucket_time,\n    avg(state_of_charge) as soc\n  FROM electricity_storage\n  WHERE\n    state_of_charge > 0 AND\n    $__timeFilter(\"time\")\n  GROUP BY bucket_time\n  ORDER BY bucket_time DESC\n) AS s\n"
    }
   ]
  },
  { "title": "💨 Ventilation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Average temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket_time as time,\n  avg_extracted as \"Extracted air\",\n  avg_supplied_after_heat_recovery as \"Supplied after heat recovery\",\n  avg_supplied_after_ground as \"Supplied air after ground\"\nFROM (\n  SELECT\n    time_bucket('1 day', time) + interval '12 hours' as bucket_time,\n    avg(extracted_temperature) as avg_extracted,\n    avg(supplied_temperature_after_heat_recovery_exchanger) as avg_supplied_after_heat_recovery,\n    avg(supplied_temperature_after_ground_coupled_heat_exchanger) as avg_supplied_after_ground\n  FROM air\n  WHERE\n    $__timeFilter(\"time\")\n  GROUP BY bucket_time\n  ORDER BY bucket_time DESC\n) AS s\n"
    }
   ]
  },
  {
   "title": "Domestic Hot Water Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket_time as time,\n  average_temp as \"Average temperature\"\nFROM (\n  SELECT\n    time_bucket('1 day', time) + interval '12 hours' as bucket_time,\n    avg((top_of_the_tank_temperature + bottom_of_the_tank_temperature) / 2) as average_temp\n  FROM domestic_hot_water\n  WHERE\n    $__timeFilter(\"time\")\n  GROUP BY bucket_time\n  ORDER BY bucket_time DESC\n) AS s\n"
    }
   ]
  }
 ]
}