{
 "title": "Live",
 "time": { "from": "now-18h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "⚡️ Electricity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "House Power Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  house_power as \"Total\",\n  house_l1_power as \"Power #1\",\n  house_l2_power as \"Power #2\",\n  house_l3_power as \"Power #3\"\nFROM electricity_consumption\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  state_of_charge\nFROM electricity_storage\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Battery Ongoing Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ongoing_power as \"Ongoing Power\"\nFROM electricity_storage\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  power as \"Power\"\nFROM electricity_production\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  frequency as \"Frequency\"\nFROM electricity_production\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  temperature\nFROM electricity_storage\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time\nLIMIT 1"
    }
   ]
  },
  { "title": "💨 Ventilation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Ventilation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  supplied_temperature_after_ground_coupled_heat_exchanger as \"Supplied after ground-coupled heat exchanger\",\n  supplied_temperature_after_heat_recovery_exchanger as \"Supplied after heat recovery exchanger\",\n  extracted_temperature as \"Extracted\",\n  discharged_temperature as \"Discharged\"\nFROM air\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  inside_humidity as \"humidity\"\nFROM air\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "🚿 Domestic Hot Water",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  },
  {
   "title": "Domestic Hot Water",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  top_of_the_tank_temperature as \"Top of the tank\",\n  bottom_of_the_tank_temperature as \"Bottom of the tank\"\nFROM domestic_hot_water\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}